<a href="https://colab.research.google.com/github/dudgns407/MaritimeDataMining/blob/main/6week_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

은행정보로 신용등급을 예측하시오

In [ ]:
#1. 문제정의
#target: Crddit_Score
      #(1) 예측 컬럼 : 예측해야 할 값은 어떤 컬럼인지 알려준다.
#평가: f1-macro
      #(2) 평가방식 : 문제에서 평가하고자 하는 평가지표를 알려준다. 평가지표로 검증을 진행한다.
      #분류 : 정확도(Accuracy), 정밀도(Precision), 재현율(Recall), F1 Score, ROC-AUC
      #회귀 : MSE, MAE, 결정계수(R-squared), RMSE
#최종파일: result.csv(컬럼 1개: pred)


# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("score_train.csv")
# test = pd.read_csv("score_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_test.csv")

# 3. 탐색적 데이터 분석(EDA)
# (1)데이터 크기 확인
print("===== 데이터 크기 =====")
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)
print("\n") # 줄 바꿈

# (2)컬럼별 자료형 확인
print("===== 데이터 정보(자료형) =====")
print(train.info())
print("\n")

# (3)결측치 확인
print("===== train 결측치 수 =====")
print(train.isnull().sum().sum())
# 데이터프레임 전체의 결측치(NaN/Null) 개수를 하나의 숫자로 얻어내기 위함
print("\n")

print("===== test 결측치 수 =====")
print(test.isnull().sum().sum())
print("\n")

# (4)target 확인 -> 분류 group 개수 확인
print("===== target 빈도 =====")
print(train['Credit_Score'].value_counts())
# Series 객체에 적용되며, 해당 Series 내부에 있는 고유한 값(Unique Values)들의 빈도수를 계산

# 4. 데이터 전처리
# 원핫인코딩 (target컬럼이 object형이라 제외)
target = train.pop('Credit_Score')

train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

print("\n ===== 분할된 데이터 크기 =====")
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

# 6. 머신러닝 학습 및 평가
# 분류를 위한 지도학습에서 데이터를 학습시키고 예측하는 가장 기본적인 Scikit-learn 표준 파이프라인으로 랜덤 포레스트 분류기(RandomForestClassifier) 모델을 사용함.
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, average='macro')
print('\n f1-macro:', f1)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

# 제출파일 확인
print("\n ===== 제출파일 (샘플 5개) =====")
print(pd.read_csv("result.csv").head())

===== 데이터 크기 =====
Train Shape: (4198, 21)
Test Shape: (1499, 20)


===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4198 entries, 0 to 4197
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       4198 non-null   float64
 1   Num_of_Delayed_Payment    4198 non-null   float64
 2   Num_Credit_Inquiries      4198 non-null   float64
 3   Credit_Utilization_Ratio  4198 non-null   float64
 4   Credit_History_Age        4198 non-null   float64
 5   Payment_of_Min_Amount     4198 non-null   object
 6   Amount_invested_monthly   4198 non-null   float64
 7   Monthly_Balance           4198 non-null   float64
 8   Credit_Mix                4198 non-null   object
 9   Payment_Behaviour         4198 non-null   object
 10  Age                       4198 non-null   float64
 11  Annual_Income             4198 non-null   float64
 12  Num_Bank_Accounts         4198 non-null   float64
 13  Num_Credit_Card           4198 non-null   float64
 14  Interest_Rate             4198 non-null   float64
 15  Num_of_Loan               4198 non-null   float64
 16  Monthly_Inhand_Salary     4198 non-null   float64
 17  Changed_Credit_Limit      4198 non-null   float64
 18  Outstanding_Debt          4198 non-null   float64
 19  Total_EMI_per_month       4198 non-null   float64
 20  Credit_Score              4198 non-null   object
dtypes: float64(17), object(4)
memory usage: 688.9+ KB
None


===== train 결측치 수 =====
0


===== test 결측치 수 =====
0


===== target 빈도 =====
Credit_Score
Standard    2225
Poor        1232
Good         741
Name: count, dtype: int64

 ===== 분할된 데이터 크기 =====
(3358, 29) (840, 29) (3358,) (840,)

 f1-macro: 0.7004593488873695

 ===== 제출파일 (샘플 5개) =====
       pred
0      Poor
1      Good
2  Standard
3      Good
4  Standard

차량의 특징 기반 데이터를 활용하여 중고차 가격을 예측

In [ ]:
#1. 문제정의
#target: price
      #(1) 예측 컬럼 : 예측해야 할 값은 어떤 컬럼인지 알려준다.
#평가: RMSE(Root Mean Square Error)
      #(2) 평가방식 : 문제에서 평가하고자 하는 평가지표를 알려준다. 평가지표로 검증을 진행한다.
      #분류 : 정확도(Accuracy), 정밀도(Precision), 재현율(Recall), F1 Score, ROC-AUC
      #회귀 : MSE, MAE, 결정계수(R-squared), RMSE

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd
# train = pd.read_csv("train.csv")
# test = pd.read_csv("ltest.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/test.csv")

In [ ]:
# 3. 탐색적 데이터 분석(EDA)
# (1) 데이터 크기 확인
train.shape, test.shape

((3759, 9), (1617, 8))

In [ ]:
# 샘플 확인
train.head(3)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,EcoSport,2017,10298,Manual,25013,Petrol,150,53.3,1.0
1,Focus,2016,10491,Manual,30970,Diesel,0,74.3,1.5
2,S-MAX,2017,13498,Manual,60200,Diesel,150,56.5,2.0

In [ ]:
# (2)컬럼별 자료형 확인
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3759 entries, 0 to 3758
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         3759 non-null   object
 1   year          3759 non-null   int64
 2   price         3759 non-null   int64
 3   transmission  3759 non-null   object
 4   mileage       3759 non-null   int64
 5   fuelType      3759 non-null   object
 6   tax           3759 non-null   int64
 7   mpg           3759 non-null   float64
 8   engineSize    3759 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 264.4+ KB

In [ ]:
train.describe()

,year,price,mileage,tax,mpg,engineSize
count,3759.000000,3759.000000,3759.000000,3759.000000,3759.000000,3759.000000
mean,2016.887736,12353.321362,23191.786379,114.444001,57.793083,1.352807
std,2.151811,4750.338051,19223.258713,61.713682,10.099221,0.437130
min,2002.000000,1095.000000,5.000000,0.000000,20.900000,0.000000
25%,2016.000000,9000.000000,9997.500000,75.000000,52.300000,1.000000
50%,2017.000000,11495.000000,18180.000000,145.000000,58.900000,1.200000
75%,2018.000000,15310.000000,31000.000000,145.000000,65.700000,1.500000
max,2060.000000,48000.000000,144000.000000,570.000000,201.800000,5.000000

In [ ]:
train.describe(include='O')

          model transmission fuelType
count      3759         3759     3759
unique       19            3        3
top      Fiesta       Manual   Petrol
freq       1372         3234     2541

In [ ]:
# (3)결측치 확인
train.isnull().sum().sum()

np.int64(0)

In [ ]:
test.isnull().sum().sum()

np.int64(0)

In [ ]:
train['price'].value_counts()
# value_counts() 결과가 수백개 이상 나오면 회귀로 판단

price
12000    33
9000     31
11000    30
11500    27
10000    27
         ..
5700      1
7481      1
8194      1
11895     1
18591     1
Name: count, Length: 1443, dtype: int64

In [ ]:
# 4. 데이터 전처리
target = train.pop('price')

print(train.shape, test.shape)
train = pd.get_dummies(train)
test = pd.get_dummies(test)
print(train.shape, test.shape)

(3759, 8) (1617, 8)
(3759, 30) (1617, 30)

In [ ]:
# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
X_tr.shape, X_val.shape, y_tr.shape, y_val.shape

((3007, 30), (752, 30), (3007,), (752,))

In [ ]:
# 6. 머신러닝 학습 및 평가
# 회귀 분석에서 RandomForestRegressor를 사용하는 가장 큰 이유는 단일 모델(예: 단순 선형 회귀나 단일 결정 트리)이 가지는 한계를 극복하고 높은 예측 정확도(overfitting 방지)와 안정성(이상치에 강함)을 확보

from sklearn.metrics import root_mean_squared_error

In [ ]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)
root_mean_squared_error(y_val, pred)

1341.943732584459

In [ ]:
# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
result = pd.DataFrame({
    'pred':pred
})
result.to_csv("result.csv", index=False)

# 제출파일 확인
pd.read_csv('result.csv')

          pred
0     15586.88
1     15407.71
2     14912.47
3     18482.73
4      6168.01
...        ...
1612  10887.99
1613  17320.61
1614   9299.85
1615  14523.67
1616   4921.74

[1617 rows x 1 columns]